channels:
- conda-forge
dependencies:
- pyiron_base>=0.2.6    # simulation framework 
- temmeta=0.0.6         # TEM image post processing
- pystem =0.0.25        # image segmentation
- match-series          # ridge deformation 
- hyperspy=1.6.1        # spectroscopy
- scanf                 # file path utility 
- papermill             # execute notebooks 
